spring.application.name=common
spring.data.mongodb.uri=mongodb://localhost:27017
spring.data.mongodb.database=GSS
okta.client.token=00YM7oDMvLMiYpss5EkFkiUDXHuD9-nPyDoor9izpB
okta.client.orgUrl=https://dev-21712882.okta.com
